import type { MetadataRoute } from 'next';

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      { userAgent: '*', allow: '/' },
      { userAgent: 'Googlebot', allow: '/' },
      { userAgent: 'Googlebot-Image', allow: '/' },
      { userAgent: 'Googlebot-News', allow: '/' },
      { userAgent: 'Bingbot', allow: '/' },
      { userAgent: 'Slurp', allow: '/' },
      { userAgent: 'DuckDuckBot', allow: '/' },
      { userAgent: 'Baiduspider', allow: '/' },
      { userAgent: 'YandexBot', allow: '/' },
      { userAgent: 'Sogou', allow: '/' },
      { userAgent: 'Exabot', allow: '/' },
      { userAgent: 'Teoma', allow: '/' },
      { userAgent: 'Aolbot', allow: '/' },
      { userAgent: 'Applebot', allow: '/' },
      { userAgent: 'ecosia-bot', allow: '/' },
      { userAgent: 'Ask Jeeves/Teoma', allow: '/' },
      { userAgent: 'NaverBot', allow: '/' },
      { userAgent: 'SeznamBot', allow: '/' },
      { userAgent: '360Spider', allow: '/' },
      { userAgent: 'Daumoa', allow: '/' },
      { userAgent: 'swisscows', allow: '/' },
      { userAgent: 'Qwantify', allow: '/' },
      { userAgent: 'Facebot', allow: '/' },
      { userAgent: 'LinkedInBot', allow: '/' },
      { userAgent: 'Twitterbot', allow: '/' },
      { userAgent: 'GPTBot', allow: '/' },
      { userAgent: 'ChatGPT-User', allow: '/' },
      { userAgent: 'OpenAI-Python', allow: '/' },
      { userAgent: 'ClaudeBot', allow: '/' },
      { userAgent: 'PerplexityBot', allow: '/' },
      { userAgent: 'CCBot', allow: '/' },
      { userAgent: 'Meta-ExternalAgent', allow: '/' },
      { userAgent: 'HuggingChat', allow: '/' },
      { userAgent: 'GrokBot', allow: '/' },
      { userAgent: 'CopilotBot', allow: '/' },
      { userAgent: 'CodeWhispererBot', allow: '/' },
      { userAgent: 'JasperBot', allow: '/' },
      { userAgent: 'ChatsonicBot', allow: '/' },
      { userAgent: 'GeminiBot', allow: '/' },
      { userAgent: 'BardBot', allow: '/' },
      { userAgent: 'PiBot', allow: '/' },
      { userAgent: 'PoeBot', allow: '/' },
      { userAgent: 'TabnineBot', allow: '/' },
      { userAgent: 'ElicitBot', allow: '/' },
      { userAgent: 'ContentShakeBot', allow: '/' },
      { userAgent: 'YouBot', allow: '/' },
      { userAgent: 'DeepSeek', allow: '/' },
      { userAgent: 'CharacterAI', allow: '/' },
      { userAgent: 'Writesonic', allow: '/' },
      { userAgent: 'AiToolsForEverydayTasks', allow: '/' },
      { userAgent: 'BlackboxBot', allow: '/' },
    ],
    sitemap: 'https://www.usmarketpartner.com/sitemap.xml',
  };
}
